version: '3.1'

# services:
#   web:
#     build: .
#     volumes:
#       - .:/usr/app/
#       - ../front/index.html:/usr/app/index.html
#     env_file:
#       - .env
#     depends_on:
#       - postgres
#     environment: 
#       POSTGRES_PORT: ${POSTGRES_PORT}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_HOST: ${POSTGRES_HOST}
#     ports:
#       - "8082:${PORT}"
#   postgres:
#     build: ../pgdata/.
#     env_file:
#       - .env
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_HOST: ${POSTGRES_HOST}
#       POSTGRES_PORT: ${POSTGRES_PORT}
#     container_name: ${POSTGRES_HOST}


    

services:
  web:
    build: .
    volumes:
      - .:/usr/app/
      - ../front/index.html:/app/index.html
    env_file:
      .env
    depends_on:
      - postgres
    environment: 
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "3005:${PORT}"
  postgres:
    build: ../pgdata/.
    restart: always
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}